language: rust
sudo: required
rust:
    - nightly-2020-06-09

cache:
    cargo: true
before_cache: rm -rf "$TRAVIS_HOME/.cargo/registry/src" 

env:
    global:
        - RUST_BACKTRACE=1

        - db_username='postgres'
        - db_port=5432
        - db_host='localhost'
        - db_pass='poshy'
        - db_name='gotdb'
        - test_db_name='gotdb_test'

        - DATABASE_URL=postgres://$db_username:$db_pass@$db_host:$db_port/$db_name
        - TEST_DATABASE_URL=postgres://$db_username:$db_pass@$db_host:$db_port/$test_db_name


install:
    #- rustup override set nightly-2019-12-20
    - rustup component add clippy --toolchain nightly-2020-06-09
    - rustup component add rustfmt --toolchain nightly-2020-06-09
    - cargo install diesel_cli --vers 1.4.0 --no-default-features --features postgres

before_install:
    - export PACKAGE=postgresql-11-postgis-2.5
    - sudo service postgresql stop
    - sudo apt-get --yes remove postgresql-10-postgis-2.4
    - sudo apt-get install $(apt-cache depends $PACKAGE | grep Depends | sed "s/.*ends:\ //" | tr '\n' ' ')
    - sudo apt install --yes postgresql-11-postgis-2.5-scripts postgresql-11 postgresql-client-11 postgresql-11-postgis-2.5
    - sed -e 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf > postgresql.conf
    - sudo chown postgres postgresql.conf
    - sudo mv postgresql.conf /etc/postgresql/11/main
    - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
    - sudo service postgresql restart 11


before_script:
  - export PATH="/usr/lib/postgresql/11/bin:$PATH"
  - diesel database setup --locked-schema --migration-dir=src/diesel_cfg/migrations/


script:
    - cargo +nightly-2020-06-09 fmt -- --check
    - cargo +nightly-2020-06-09 clippy --all-targets --all-features --all
    - cargo build
    - cargo test

notifications:
  email:
    on_success: never
