[package]
name = "got-ya-id"
version = "0.1.0"
authors = ["mugoh <mugoh.ks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
listenfd = "0.3"
serde = "1.0.101"
validator = "0.9.0"
validator_derive = "0.9.0"
serde_derive = "1.0.101"
serde_json = "1.0.40"
lazy_static = "1.4.0"
regex = "1"

